### ISSUE TITLE
[tag:so-review-links.user.js] breaks "ask question" page

### ISSUE THREAD

**Issue by ferrybig** [Gothdo/UserScripts#2]
When using the [so-review-links](https://github.com/Gothdo/UserScripts/blob/master/so-review-links.user.js), the [ask question page](https://stackoverflow.com/questions/ask) breaks on StackOverflow, it removes all editor buttons, and prevents the preview from working.

`Uncaught Error: getQuestionId could not find an id(…)`

Userscript version: 1.1

**Comment by Gothdo** [comment]
This userscript no longer works, because the timeline no longer shows information about review queues in which a question currently is. See [Allow us again to see if a question is currently on the close review queues](http://meta.stackoverflow.com/q/319682/3853934).
